# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty

# Setup
title:            Miguel Zarco
#tagline:          'A Jekyll theme'
description:      Profile description should go here
url:              #http://hyde.getpoole.com
baseurl:          /

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
