# Permalinks
permalink:        pretty

# Setup
title:            Miguel Zarco
tagline:          Developer
subtitle:         Developing software for the 4.0 industry

url:              https://mikelinhas.github.io
baseurl:          /


github:
  repo:           https://github.com/mikelinhas

linkedin:         https://linkedin.com/in/miguelzarco
